# Generated by Django 3.1.6 on 2021-02-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210210_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmanagment',
            name='Company',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='shopmanagment',
            name='Type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
